export const sidebarGroups: NavGroup[] = [
  {
    id: "getting-started",
    title: "基礎入門",
    icon: "heroicons:rocket-launch",
    items: [
      {
        label: "文件導覽",
        to: "/docs",
        icon: "heroicons:book-open",
        description: "文件導覽與結構說明。",
        badges: [{ label: "Intro", color: "neutral" }],
      },
      {
        label: "安裝指南",
        to: "/docs/1-getting-started/installation",
        icon: "heroicons:command-line",
        description: "建立專案、執行開發模式、理解常用指令。",
        badges: [
          { label: "Beginner", color: "primary" },
          { label: "Setup", color: "neutral" },
        ],
      },
      {
        label: "目錄結構",
        to: "/docs/1-getting-started/directory-structure",
        icon: "heroicons:folder",
        description: "認識 app/、server/、public/ 等目錄的角色。",
        badges: [{ label: "Beginner", color: "primary" }],
      },
      {
        label: "路由系統",
        to: "/docs/1-getting-started/routing",
        icon: "heroicons:map",
        description: "檔案即路由 (File-based Routing) 的運作機制。",
        badges: [{ label: "Core Concept", color: "primary" }],
      },
      {
        label: "版型結構",
        to: "/docs/1-getting-started/layouts",
        icon: "heroicons:rectangle-group",
        description: "共用版型與巢狀佈局。",
        badges: [{ label: "UI Layout", color: "neutral" }],
      },
      {
        label: "樣式系統",
        to: "/docs/1-getting-started/styling",
        icon: "heroicons:paint-brush",
        description: "Tailwind CSS 設定與使用。",
        badges: [{ label: "Styling", color: "neutral" }],
      },
      {
        label: "UI 生態系",
        to: "/docs/1-getting-started/ui-libraries",
        icon: "heroicons:swatch",
        description: "Nuxt UI 與 Icon 系統。",
        badges: [{ label: "Components", color: "neutral" }],
      },
      {
        label: "靜態資源",
        to: "/docs/1-getting-started/assets",
        icon: "heroicons:photo",
        description: "圖片、字型引用方式。",
        badges: [{ label: "Assets", color: "neutral" }],
      },
      {
        label: "導航連結",
        to: "/docs/1-getting-started/nuxt-link",
        icon: "heroicons:link",
        description: "NuxtLink 的最佳實踐。",
        badges: [{ label: "Best Practice", color: "white" }],
      },
    ],
  },
  {
    id: "core-concepts",
    title: "核心修練",
    icon: "heroicons:cpu-chip",
    items: [
      {
        label: "自動引入",
        to: "/docs/2-core-concepts/auto-imports",
        icon: "heroicons:sparkles",
        description: "理解 Nuxt 的自動引入黑魔法。",
        badges: [{ label: "Magic", color: "sky" }],
      },
      {
        label: "資料獲取",
        to: "/docs/2-core-concepts/data-fetching",
        icon: "heroicons:cloud-arrow-down",
        description: "useAsyncData 與 useFetch 詳解。",
        badges: [
          { label: "Critical", color: "primary" },
          { label: "Async", color: "neutral" },
        ],
      },
      {
        label: "伺服路由",
        to: "/docs/2-core-concepts/server-routes",
        icon: "heroicons:server",
        description: "建立 API Endpoints 與後端邏輯。",
        badges: [
          { label: "Backend", color: "neutral" },
          { label: "Nitro", color: "sky" },
        ],
      },
      {
        label: "狀態管理",
        to: "/docs/2-core-concepts/state-management",
        icon: "heroicons:circle-stack",
        description: "useState 與 Pinia 的使用時機。",
        badges: [{ label: "State", color: "neutral" }],
      },
      {
        label: "共用邏輯",
        to: "/docs/2-core-concepts/composables-utils",
        icon: "heroicons:cube-transparent",
        description: "封裝與重用商業邏輯。",
        badges: [{ label: "Reusability", color: "neutral" }],
      },
      {
        label: "環境變數",
        to: "/docs/2-core-concepts/runtime-config",
        icon: "heroicons:cog-6-tooth",
        description: "Runtime Config 與機密資料管理。",
        badges: [{ label: "Config", color: "neutral" }],
      },
    ],
  },
  {
    id: "advanced",
    title: "進階架構",
    icon: "heroicons:building-library",
    items: [
      {
        label: "路由守衛",
        to: "/docs/3-architecture/route-middleware",
        icon: "heroicons:shield-check",
        description: "路由權限驗證與攔截。",
        badges: [{ label: "Security", color: "orange" }],
      },
      {
        label: "外掛系統",
        to: "/docs/3-architecture/plugins",
        icon: "heroicons:puzzle-piece",
        description: "擴充 Nuxt 功能與第三方套件。",
        badges: [{ label: "Advanced", color: "neutral" }],
      },
      {
        label: "渲染模式",
        to: "/docs/3-architecture/rendering-modes",
        icon: "heroicons:computer-desktop",
        description: "SSR, CSR, SSG 與 Hybrid Rendering。",
        badges: [
          { label: "Performance", color: "primary" },
          { label: "SSR/SSG", color: "sky" },
        ],
      },
      {
        label: "SEO 設定",
        to: "/docs/3-architecture/seo",
        icon: "heroicons:magnifying-glass",
        description: "動態 Meta Tags 與 Open Graph。",
        badges: [
          { label: "Marketing", color: "emerald" },
          { label: "SEO", color: "neutral" },
        ],
      },
      {
        label: "圖片優化",
        to: "/docs/3-architecture/nuxt-img",
        icon: "heroicons:camera",
        description: "使用 Nuxt Image 進行自動優化。",
        badges: [{ label: "Performance", color: "primary" }],
      },
      {
        label: "錯誤處理",
        to: "/docs/3-architecture/error-handling",
        icon: "heroicons:exclamation-triangle",
        description: "自訂錯誤頁面與異常捕獲。",
        badges: [{ label: "Stability", color: "orange" }],
      },
      {
        label: "生命週期",
        to: "/docs/3-architecture/lifecycle",
        icon: "heroicons:clock",
        description: "深入 Nuxt/Vue 執行流。",
        badges: [{ label: "Deep Dive", color: "neutral" }],
      },
    ],
  },
  {
    id: "devops",
    title: "工程與部署",
    icon: "heroicons:wrench-screwdriver",
    items: [
      {
        label: "版本控制",
        to: "/docs/4-devops/git",
        icon: "simple-icons:git",
        description: "專案版本控制與協作規範。",
        badges: [{ label: "Git", color: "neutral" }],
      },
      {
        label: "型別系統",
        to: "/docs/4-devops/typescript",
        icon: "heroicons:code-bracket",
        description: "型別安全與開發體驗。",
        badges: [{ label: "TypeScript", color: "blue" }],
      },
      {
        label: "模組開發",
        to: "/docs/4-devops/modules",
        icon: "heroicons:squares-plus",
        description: "封裝可重用的 Nuxt 模組。",
        badges: [{ label: "Advanced", color: "neutral" }],
      },
      {
        label: "測試策略",
        to: "/docs/4-devops/testing",
        icon: "heroicons:beaker",
        description: "單元測試與 E2E 測試。",
        badges: [{ label: "Quality", color: "primary" }],
      },
      {
        label: "設定安全",
        to: "/docs/4-devops/security",
        icon: "heroicons:lock-closed",
        description: "資安防護最佳實踐。",
        badges: [{ label: "Security", color: "red" }],
      },
      {
        label: "多國語言",
        to: "/docs/4-devops/i18n",
        icon: "heroicons:language",
        description: "國際化網站建置。",
        badges: [{ label: "i18n", color: "neutral" }],
      },
      {
        label: "效能優化",
        to: "/docs/4-devops/performance",
        icon: "heroicons:chart-bar",
        description: "Bundle 分析與載入速度。",
        badges: [{ label: "Performance", color: "primary" }],
      },
      {
        label: "部署指南",
        to: "/docs/4-devops/deployment",
        icon: "heroicons:rocket-launch",
        description: "各類平台部署指南。",
        badges: [{ label: "Deployment", color: "sky" }],
      },
    ],
  },
];
